name: CI/CD workflow

on:
  push:
    branches:
      - master
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install deps
        run: npm ci

      - name: Formatting and linting
        run: |
          npm run format:check
          npm run lint
          npm run tsc:check

      - name: Tests
        run: npm run test
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: just echo one
        run: echo one one one

  test2:
    runs-on: ubuntu-18.04
    steps:
      - name: just echo two
        run: echo two two two
