name: CI/CD workflow

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    types:
      - opened

jobs:
  just-print:
    runs-on: ubuntu-latest
    env:
      fucking_secret: ${{secrets.JWT_ACCESS_SECRET}}
    steps:
      - run: echo just run the secret $fucking_secret
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install deps
        run: npm ci

      - name: Formatting and linting
        run: |
          npm run format:check
          npm run lint
          npm run tsc:check

      - name: Tests
        run: npm run test
