name: CI/CD workflow

on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install deps
        run: npm ci

  tests-and-linting:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Formatting and linting
        run: |
          npm run format:check
          npm run lint
          npm run tsc:check

      - name: Tests
        run: npm run test

      - name: Build the app
        run: npm run Build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
